### ISSUE TITLE
Parameter Discovery | URL Extraction phase generate errors when running

### ISSUE THREAD

**Issue by Hax0rG1rl** [six2dez/reconftw#224]
When scanning a target using the latest version, 1.4.1, I noticed a couple of errors like this: 

```
Parameter Discovery 

Running : Searching params with paramspider
cat: 'output/*.txt': No such file or directory

Running : Checking <target> with Arjun
usage: arjun [-h] [-u URL] [-o JSON_FILE] [-oT TEXT_FILE] [-oB BURP_PORT] [-d DELAY] [-t THREADS] [-w WORDLIST]
             [-m METHOD] [-i [IMPORT_FILE]] [-T TIMEOUT] [-c CHUNKS] [-q] [--headers [HEADERS]]
             [--passive PASSIVE] [--stable] [--include INCLUDE]
arjun: error: argument -t: expected one argument

params Finished in 1 seconds. 

URL Extraction 
invalid value "-subs" for flag -t: parse error
```

**Expected behavior**
I do expect the tools associated with the testing sequence to produce an error-free output. 

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: Kali
 - Version: Latest

**Comment by Hax0rG1rl** [comment]
Also, I noticed this error too: 

```
[*] Removing any duplicate NS server IP Addresses...
Traceback (most recent call last):
  File "/root/Tools/dnsrecon/dnsrecon.py", line 1763, in <module>
    main()
  File "/root/Tools/dnsrecon/dnsrecon.py", line 1654, in main
    returned_records.extend(std_enum_records)
TypeError: 'NoneType' object is not iterable
grep: subdomains/zonetransfer.json: No such file or directory

 zonetransfer Finished in 1 seconds. 
```

**Comment by detonxx** [comment]
1)Check whether interlace, paramspider are installed or not

2)Check the #Threads section of the config file ```reconftw.cfg``` 
The issue is occurring due to improper declaration of the threads. Verify them once.  
```
   ARJUN_THREADS=20 
   GAUPLUS_THREADS=50
```

3)The problem with the tool dnsrecon.py is not reproducible. Maybe open an issue there
