### ISSUE TITLE
Interlace: PackageNotFoundError makes axiom-scan commands fail

### ISSUE THREAD

**Issue by frost19k** [six2dez/reconftw#434]
**Describe the bug**
Interlace is misconfigured in the Docker Image. 

**To Reproduce**
```bash
❯ docker run -it --rm --entrypoint /usr/bin/interlace six2dez/reconftw:main
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.5', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
```

**Expected behavior**
```bash
❯ docker run -it --rm --entrypoint /usr/bin/interlace six2dez/reconftw:main
usage: interlace [-h] (-t TARGET | -tL FILE) [-e EXCLUSIONS | -eL FILE] [-threads THREADS]
                 [-timeout TIMEOUT] [-pL FILE] (-c COMMAND | -cL FILE) [-o OUTPUT] [-p PORT]
                 [--proto PROTO] [-rp REALPORT] [-random RANDOM] [--no-cidr] [--no-color] [--no-bar]
                 [--repeat REPEAT] [-v | --silent]
interlace: error: one of the arguments -t -tL is required

```

**Desktop (please complete the following information):**
- Architecture: x86_64
 - OS: Manjaro
 - Version: Rolling (Currently 21.2.0)

**Additional context**
`axiom-scan` requires `interlace` & thus running `reconftw.sh` with the flag `-v` returns fewer than expected results.

I have discovered that configuring `interlace` with `pip3` resolves the issue.
```bash
❯ docker run -it --entrypoint /bin/bash six2dez/reconftw:main
❯ cd ~/Tools/Interlace
❯ python3 setup.py install --record files.txt
❯ xargs rm -rf < files.txt
❯ pip3 install .
```

https://user-images.githubusercontent.com/49780407/147375528-7696263a-f8ee-4437-a515-a94e8da1e9b0.mp4

**Comment by frost19k** [comment]
Alright, it's not just interlace - it's quite possibly every python tool in the tool chain.

`pip3 install .` seems to work for most. Some (like `theHarvester`) require re-installation of `requirements.txt`.

I'd be super interested to know whether people running `reconFTW` in a OS environment (rather than a Docker container) are having similar issues - and what version of Python they have installed.

```bash
❯ docker run -t --rm --entrypoint wafw00f six2dez/reconftw:main
Traceback (most recent call last):
  File "/usr/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wafw00f==2.1.0' distribution was not found and is required by the application

❯ docker run -t --rm --entrypoint theHarvester six2dez/reconftw:main
Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 4, in <module>
    __import__('pkg_resources').run_script('theHarvester==4.0.3', 'theHarvester')
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'theHarvester==4.0.3' distribution was not found and is required by the application

❯ docker run -t --rm --entrypoint dnsvalidator six2dez/reconftw:main
Traceback (most recent call last):
  File "/usr/bin/dnsvalidator", line 33, in <module>
    sys.exit(load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')())
  File "/usr/bin/dnsvalidator", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: DNSValidator

```

**Comment by six2dez** [comment]
I always use it installed in OS instead Docker version :P

**Comment by six2dez** [comment]
Thx for the PR it should be fixed now, closing issue.

**Comment by frost19k** [comment]
@six2dez Okay, firstly Docker is *the* best pentest platform. It offers the isolation of a VM with the hardware access of "on-metal". You want access to your WiFi NIC? `--network host`. You want to run a GPU accelerated tool `--gpus all`. I am prepared to die on this hill 😝 

More importantly, I don't quite understand **why** the fix works. I wish someone could shed some light 'cause it's really bothering me.

Also, `pip3 install -r requirements.txt` is a lazy solution & is bound to cause dependency problems down the road.
