### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by vansh1** [six2dez/reconftw#454]
**Describe the bug**
  File "/usr/local/bin/s3scanner", line 5, in <module>
    from S3Scanner.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/S3Scanner/__main__.py", line 15, in <module>
    from .S3Service import S3Service
  File "/usr/local/lib/python3.8/dist-packages/S3Scanner/S3Service.py", line 5, in <module>
    from boto3 import client  # TODO: Limit import to just boto3.client, probably
  File "/usr/local/lib/python3.8/dist-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.8/dist-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.8/dist-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.8/dist-packages/botocore/credentials.py", line 35, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.8/dist-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.8/dist-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.8/dist-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.8/dist-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.8/dist-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py)

**To Reproduce**
normally ran command ./reconftw.sh -d xyx.com -r -s, and at the last this came

**Expected behavior**
there shouldn't be any error

**Desktop (please complete the following information):**
ubuntu
20.04.1

**Comment by six2dez** [comment]
Seems more an error from s3scanner than reconftw, try to reinstall and check again plz
