### ISSUE TITLE
Fuzzing Bug

### ISSUE THREAD

**Issue by VVaReD** [six2dez/reconftw#539]
after install..fuzz_wordlist.txt is empty...
download it manually...fuzzing still not running..

**Comment by VVaReD** [comment]
ok its fixing a problem with interlace 

interlace
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 5, in <module>
    from Interlace.interlace import main
  File "/usr/local/lib/python3.10/dist-packages/Interlace/interlace.py", line 6, in <module>
    from Interlace.lib.core.output import OutputHelper, Level
  File "/usr/local/lib/python3.10/dist-packages/Interlace/lib/core/output.py", line 4, in <module>
    from colorclass import Color
  File "/usr/local/lib/python3.10/dist-packages/colorclass/__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
  File "/usr/local/lib/python3.10/dist-packages/colorclass/codes.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

change in codes.py : from collections import Mapping to from collections.abc import Mapping

**Comment by six2dez** [comment]
Try installing interlace manually plz
