### ISSUE TITLE
 Docker - AWS S3 buckets search crash

### ISSUE THREAD

**Issue by sven-hash** [six2dez/reconftw#557]
**Describe the bug**

`cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py)` on docker container

**To Reproduce**
Fail at 

```
 AWS S3 buckets search
 AWS S3 buckets search  - fleurdepains.ch
Traceback (most recent call last):
  File "/usr/local/bin/s3scanner", line 5, in <module>
    from S3Scanner.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/S3Scanner/__main__.py", line 15, in <module>
    from .S3Service import S3Service
  File "/usr/local/lib/python3.10/dist-packages/S3Scanner/S3Service.py", line 5, in <module>
    from boto3 import client  # TODO: Limit import to just boto3.client, probably
  File "/usr/local/lib/python3.10/dist-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session                                                                                                     File "/usr/local/lib/python3.10/dist-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.10/dist-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.10/dist-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/lib/python3.10/dist-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/lib/python3.10/dist-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/lib/python3.10/dist-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/lib/python3.10/dist-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/lib/python3.10/dist-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/lib/python3.10/dist-packages/botocore/utils.py", line 34, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.10/dist-packages/botocore/httpsession.py", line 21, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py)

```
**Expected behavior**
Normal output

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: Ubuntu
 - Version 22.04
 - Docker version: Docker version 20.10.17, build 100c701

**Additional context**

**Comment by six2dez** [comment]
Seems to be the same as #522 something related to python 3.10 and Docker :/

**Comment by frost19k** [comment]
This is the same as #477
