### ISSUE TITLE
web manage execute_from_command_line(sys.argv)

### ISSUE THREAD

**Issue by d1xc1xc** [six2dez/reconftw#685]
## Hello 👋

./install.sh
```
 Creating WEB User...

rm: cannot remove '/home/recon/reconftw/web/db.sqlite3': No such file or directory
Traceback (most recent call last):
  File "/home/recon/reconftw/web/manage.py", line 22, in <module>
    main()
  File "/home/recon/reconftw/web/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/recon/reconftw/web/web/urls.py", line 7, in <module>
    from scans import views
  File "/home/recon/reconftw/web/scans/views.py", line 37
    match type_scan:
          ^
SyntaxError: invalid syntax
 Remember set your api keys:
 - amass (~/.config/amass/config.ini)
 - subfinder (~/.config/subfinder/provider-config.yaml)
 - GitLab (~/Tools/.gitlab_tokens)
 - SSRF Server (COLLAB_SERVER in reconftw.cfg or env var)
 - Blind XSS Server (XSS_SERVER in reconftw.cfg or env var)
 - notify (~/.config/notify/provider-config.yaml)
 - theHarvester (~/Tools/theHarvester/api-keys.yaml or /etc/theHarvester/api-keys.yaml)
 - WHOISXML API (WHOISXML_API in reconftw.cfg or env var)


 Finished!

```

 Please correct, thank you

**Comment by davidfegyver** [comment]
Hey! 
I think you have to install python 10 in your system. The match case statement was introduced in that version.

**Comment by d1xc1xc** [comment]
Hey!

works python 10 

```
#!/bin/bash
# Get the installed Python version
python_version=$(python3 --version 2>&1)
if [[ $python_version == "Python 3."[1-9][0-9]* || $python_version == "Python 3.10"* ]]; then
  echo "ok"
else
  sudo apt install python3.10-venv ; python3.10 -m venv .venv ; source .venv/bin/activate ; pip install -r requirements.txt ; python3 manage.py migrate
fi
```
