### ISSUE TITLE
xnLinkFinder BUG

### ISSUE THREAD

**Issue by burper00** [six2dez/reconftw#858]
My system everything is updated but I still get that error. When I trying on console command xnLinkFinder is working fine. How to fix it ?

![ask1](https://github.com/six2dez/reconftw/assets/157926181/907716ab-e85e-4087-8701-2c01297a9f98)
![ask2](https://github.com/six2dez/reconftw/assets/157926181/ce30b4e6-b125-40bc-b18b-1153c49f12c3)
![ask3](https://github.com/six2dez/reconftw/assets/157926181/4a16fc67-c359-4cff-87ca-96b095d9030b)

Virtualbox kali linux 2024.01 Updated.
Reconftw updated.
python version Python 3.11.8

When going error line I dont see anything its seems good

Traceback (most recent call last):
  File "/root/Tools/xnLinkFinder/xnLinkFinder/xnLinkFinder.py", line 4115, in <module>
    main()
  File "/root/Tools/xnLinkFinder/xnLinkFinder/xnLinkFinder.py", line 3659, in main
    description="xnlLinkFinder (v" + __import__('xnLinkFinder').__version__ + ") - by @Xnl-h4ck3r"
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'xnLinkFinder' has no attribute '__version__'

**Comment by burper00** [comment]
Thanks for answer! Thats what I saying actually. When I trying to command console its working. But real question is how to fix together work Reconftw and xnLinkFinder ? How to change work location.

**Comment by burper00** [comment]
oh here is fix https://github.com/six2dez/reconftw/pull/853 Finally! but is should be updated offically changes to " git clone https://github.com/six2dez/reconftw.git " :)
